apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: git-server
  name: git-server
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    service: git-server
status:
  loadBalancer: {}
